Repository ExplorerTheArea/Experia, pull requests merged in 2025-09, with the labels that each got.

#138 [P6-108] 회원가입 페이지
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.tsx
  src/types/schema/userSchema.ts
Labels: component 🧩

#142 팝오버 페이지 작업
  next.config.ts
  src/components/calender/popOver/PopOver.tsx
  src/components/calender/popOver/api-server.ts
  src/components/calender/popOver/updateReserveStatus/UpdateReserveStatus.tsx
  src/components/calender/popOver/utils/PopOver.function.ts
  src/types/schema/activitiesSchema.ts
  src/utils/api-public/api-my-activities.api.ts
  src/utils/api-public/index.ts
Labels: component 🧩

#154 [P6-121] axios 인터셉터 구현 + 토큰 재발급
  package-lock.json
  package.json
  src/app/(auth)/signin/page.tsx
  src/app/(global)/mypage/components/MyInfoClient.tsx
  src/app/(global)/mypage/components/MyInfoForm.tsx
  src/app/(global)/mypage/page.tsx
  src/constants/index.ts
  src/utils/axios/apiAuth.ts
Labels: feature ✨

#160 [P6-117] Modal 공용 컴포넌트 생성
  public/icons/ic_Close.svg
  src/app/test/layout.tsx
  src/app/test/page.tsx
  src/components/popup.tsx
  src/components/provider/Providers.tsx
  src/components/reviews/AddReviewModal.tsx
  src/components/ui/Modal/ModalProvider.tsx
  src/components/ui/Modal/index.tsx
  src/stores/modalStore.ts
Labels: component 🧩

#177 [P6-126] 체험상세 페이지 케밥 버튼 구현 (phase 4)
  public/icons/ActivityPageImgs/ic_CautionSign.svg
  src/app/(global)/activities/[id]/components/Post.tsx
  src/app/(global)/activities/[id]/components/Reservation.tsx
  src/app/(global)/activities/[id]/components/layout/PostHeader.tsx
  src/app/(global)/activities/[id]/page.tsx
  src/components/DropdownMeatball.tsx
  src/components/activities/Modals/DeleteModal.tsx
Labels: feature ✨, component 🧩

#174 [P6-118] 알림 기능 구현
  src/app/globals.css
  src/assets/icons/ic_closeBlack.svg
  src/components/layout/Header.tsx
  src/components/notification/NotificationItem.tsx
  src/components/notification/NotificationPopover.tsx
  src/types/schema/notificationSchema.ts
  src/utils/formatter/formatRelativeTime.ts
Labels: feature ✨, component 🧩

#184 [P6-143] feat: 헤더에 Link 마이페이지, 로그아웃 기능
  src/components/layout/Header.tsx
  src/constants/index.ts
  src/hooks/useLogout.ts
Labels: feature ✨

#185 [P6-144] fetch 기반 토큰 재발급 함수 생성 (fetchClientData)
  src/utils/api-client/fetchClientData.ts
Labels: feature ✨, api 💫

#187 [P6-135] formatPrice 유틸 함수 및 테스트 코드 생성
  jest.config.js
  jest.setup.js
  package-lock.json
  package.json
  src/utils/formatPrice.ts
  src/utils/test/formatPrice.test.ts
Labels: feature ✨

#161 [P6-116] 메인페이지 검색 기능
  public/icons/ic_SearchIcon.svg
  src/app/(global)/page.tsx
  src/components/activities/MainPage.client.tsx
  src/components/activities/SearchBar.client.tsx
  src/components/ui/Skeleton/ActivityListSkeleton.tsx
Labels: feature ✨

#190 [P6-145] feat: 내체험 관리 케밥드롭다운 추가
  src/app/(global)/activities/[id]/components/layout/PostHeader.tsx
  src/app/(global)/mypage/components/ActivityCard.tsx
  src/app/(global)/mypage/my-activities/page.tsx
  src/components/ImageUpload/ImageUploader.tsx
  src/components/ImageUpload/MultiImageUploader.tsx
  src/components/activities/Modals/DeleteModal.tsx
  src/hooks/useImageUpload.ts
  src/utils/api-client/fetchClientData.ts
Labels: feature ✨

#193 [P6-132] refactor: 내정보 수정 기능, zustand에 저장기능
  src/app/(global)/mypage/components/MyInfoClient.tsx
  src/app/(global)/mypage/components/MyInfoForm.tsx
  src/stores/userStore.ts
Labels: refactor 🔄

#196 P6 128 166 reservation page
  src/components/calender/Calender.tsx
  src/components/calender/calenderBoard/CalenderBoard.function.tsx
  src/components/calender/calenderBoard/CalenderBoard.tsx
  src/components/calender/calenderOnePart/CalenderOnePart.tsx
  src/components/calender/selectMyActivity/SelectMyActivity.tsx
  src/components/layout/Header.tsx
  src/stores/modalStore.ts
  src/utils/api-public/api-my-activities.api.ts
  src/utils/api-public/index.ts
Labels: feature ✨

#197 [P6-140] 새 알림 마크 기능
  src/components/layout/Snb.tsx
  src/components/notification/NotificationItem.tsx
  src/components/notification/NotificationPopover.tsx
  src/constants/index.ts
  src/hooks/useIntersectionObserver.ts
Labels: feature ✨

#203 [P6-138] 메인 페이지 카테고리 필터링 + 정렬
  src/app/(global)/mypage/my-reservations/page.tsx
  src/app/globals.css
  src/components/DropdownOptions.tsx
  src/components/activities/MainPage.client.tsx
  src/components/activities/SearchContainer.tsx
  src/components/notification/NotificationPopover.tsx
  src/components/ui/CategoryMenu.tsx
  src/constants/index.ts
Labels: feature ✨

#204 [P6-136] 상세페이지 예약 컴포넌트 스타일 적용 (phase 5)
  public/icons/ActivityPageImgs/ic_CloseButton.svg
  public/icons/ActivityPageImgs/ic_ReservationMinus.svg
  public/icons/ActivityPageImgs/ic_ReservationPlus.svg
  src/app/(global)/activities/[id]/components/Post.tsx
  src/app/(global)/activities/[id]/components/Reservation.tsx
  src/app/(global)/activities/[id]/components/reservateIn.tsx
  src/app/(global)/activities/[id]/components/reservation-block/Calander.tsx
  src/app/(global)/activities/[id]/components/reservation-block/Reservation.module.css
  src/app/(global)/activities/[id]/components/reservation-block/Reservation.tsx
  src/app/(global)/activities/[id]/components/reservation-block/reservateIn.tsx
  src/app/(global)/activities/[id]/components/reservation-block/reservateMobileIn.tsx
  src/components/activities/Modals/DeleteModal.tsx
Labels: style ✨

#208 [P6-141] feat: my-reservations 예약내역 필터링
  src/app/(global)/mypage/my-reservations/MyReservationsContent.tsx
  src/app/(global)/mypage/my-reservations/page.tsx
Labels: feature ✨

#209 [P6-125] 인기 체험 리스트
  package-lock.json
  package.json
  src/app/(global)/page.tsx
  src/app/globals.css
  src/components/activities/ActivityItem.tsx
  src/components/activities/MainPage.client.tsx
  src/components/activities/PopularItem.tsx
  src/components/activities/PopularList.client.tsx
  src/components/activities/PopularPage.client.tsx
  src/components/activities/SearchContainer.tsx
  src/constants/index.ts
  src/types/schema/activitiesSchema.ts
Labels: feature ✨

#248 [P6-139] 메인 성능 개선
  postcss.config.mjs
  src/app/(global)/page.tsx
  src/components/DropdownOptions.tsx
  src/components/DropdownSelect.tsx
  src/components/activities/ActivityItem.tsx
  src/components/activities/ActivityList.client.tsx
  src/components/activities/MainPage.client.tsx
  src/components/activities/PopularItem.tsx
  src/components/activities/PopularList.client.tsx
  src/components/activities/PopularPage.client.tsx
  src/components/activities/SearchBar.client.tsx
  src/components/activities/SearchContainer.tsx
  src/components/notification/NotificationItem.tsx
  src/components/notification/NotificationPopover.tsx
  src/components/ui/Section/SectionTitle.tsx
  src/components/ui/Skeleton/PopularItemSkeleton.tsx
  src/components/ui/Skeleton/PopularListSkeleton.tsx
  src/utils/formatter/formatRating.ts
Labels: feature ✨

#258 [티켓 번호 없음] Feat: 사이트 메타데이터, 사이트맵 추가
  next-sitemap.config.js
  public/robots.txt
  public/sitemap-0.xml
  public/sitemap.xml
  src/app/(auth)/layout.tsx
  src/app/(global)/layout.tsx
Labels: feature ✨
