Repository ExplorerTheArea/Experia, pull requests merged in 2025-08, with the labels that each got.

#43 P6-55-header 생성
  package-lock.json
  package.json
  public/images/ProfileDefaultImg.png
  public/images/logo.svg
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/assets/icons/AlarmIcon.svg
  src/assets/icons/ic_next.svg
  src/components/layout/Header.tsx
  src/utils/useScrollY.ts
Labels: style ✨, component 🧩, chore

#52 Chore: 헤더 - 로그인 후 스타일 주석 처리 + 알람 아이콘 vertical 정렬
  src/components/layout/Header.tsx
Labels: chore

#94 P6-86-fetchServerData 유틸 함수 생성
  src/components/layout/Header.tsx
  src/utils/api-public/api-users.api.ts
  src/utils/api-public/index.ts
  src/utils/api-server/index.ts
Labels: feature ✨

#59 P6-56-input common 공통 컴포넌트
  package-lock.json
  package.json
  src/app/(global)/page.tsx
  src/app/globals.css
  src/components/InputField.tsx
Labels: style ✨, feature ✨, component 🧩

#98 P6-68-체험 전체 목록 렌더링
  next.config.ts
  public/icons/ic_Facebook.svg
  public/icons/ic_Instagram.svg
  public/icons/ic_StarSmall.svg
  public/icons/ic_Twitter.svg
  public/icons/ic_Youtube.svg
  src/app/(global)/page.tsx
  src/components/activities/ActivityList.client.tsx
  src/components/layout/Footer.tsx
  src/components/ui/Pagination/index.tsx
  src/components/ui/Section/SectionTitle.tsx
  src/constants/index.ts
  src/types/schema/activitiesSchema.ts
Labels: feature ✨, api 💫

#125 [P6-83] chore: Add esLint import rules
  eslint.config.mjs
  package-lock.json
  package.json
Labels: chore

#120 P6-106-Avatar 컴포넌트 생성
  src/components/layout/Header.tsx
  src/components/ui/Avatar.tsx
Labels: component 🧩

#124 [P6-82] feat: 체험 상세 페이지 프레임 구현 및 API 연동 (phase 1)
  next.config.ts
  src/app/(global)/activities/[id]/page.tsx
  src/app/(global)/activities/[id]/post.tsx
  src/app/(global)/activities/[id]/postContent.tsx
  src/app/(global)/activities/[id]/postHeader.tsx
  src/app/(global)/activities/[id]/postImage.tsx
  src/app/(global)/activities/[id]/postMap.tsx
  src/app/(global)/activities/[id]/postReview.tsx
  src/app/(global)/activities/[id]/reservateIn.tsx
  src/assets/imgs/activityPage/ic_Kebab.svg
  src/assets/imgs/activityPage/ic_MarkInMap.svg
  src/assets/imgs/activityPage/ic_Star.svg
  src/assets/imgs/starRatingComp/starEmpty.svg
  src/assets/imgs/starRatingComp/starFilled.svg
  src/components/StarRating.tsx
Labels: style ✨, api 💫

#133 [P6-109] 마이페이지 레이아웃 설정, 사이드바 수정, DropdownOptions 컴포넌트 추가
  package-lock.json
  package.json
  public/icons/ic_ArrowDownFill.svg
  src/app/(global)/mypage/layout.tsx
  src/app/(global)/mypage/my-activities/page.tsx
  src/app/(global)/mypage/my-reservations/page.tsx
  src/app/(global)/mypage/reservations/page.tsx
  src/assets/icons/ic_mypage1.svg
  src/assets/icons/ic_mypage2.svg
  src/assets/icons/ic_mypage3.svg
  src/assets/icons/ic_mypage4.svg
  src/assets/icons/ic_refresh.svg
  src/components/Button.tsx
  src/components/DropdownOptions.tsx
  src/components/layout/Snb.tsx
  src/components/layout/Snb/SnbList.tsx
  src/components/ui/LinkButton.tsx
  src/components/ui/Section/SectionTitle.tsx
  src/constants/index.ts
  src/utils/cn.ts
Labels: good first issue, style ✨, component 🧩

#139 [P6-96] 체험 등록 폼 생성 (유효성 검사 + api 연동)
  package-lock.json
  src/app/(global)/mypage/components/AddActivityForm.tsx
  src/app/(global)/mypage/my-activities/add-new-activity/page.tsx
  src/app/(global)/page.tsx
  src/app/globals.css
  src/app/test/page.tsx
  src/assets/icons/CameraIcon.svg
  src/assets/icons/ic_arrowLeftLine.svg
  src/components/DropdownSelect.tsx
  src/components/ImageUpload/ImageUploadButton.tsx
  src/components/ImageUpload/ImageUploader.tsx
  src/components/ImageUpload/MultiImageUploader.tsx
  src/components/form/AddressField.tsx
  src/components/form/FormField.tsx
  src/components/form/FormLabel.tsx
  src/components/form/TextAreaField.tsx
  src/components/layout/Snb/SnbList.tsx
  src/components/ui/DateTimeInputGroup/AddDateTimeItem.tsx
  src/components/ui/DateTimeInputGroup/DateTimeItem.tsx
  src/components/ui/DateTimeInputGroup/index.tsx
  src/constants/index.ts
  src/hooks/useImageUpload.ts
  src/types/schema/activitiesSchema.ts
Labels: feature ✨, component 🧩, api 💫
